#!/bin/bash
# Based on automatic installer 
# By stsfin 
# https://github.com/stsfin/LimelightPiInstaller
version="1.2.2"
/show/description "Install limelight to stream games on TV"
/system/install oracle-java8-jdk
/system/install input-utils
/system/makedir /opt/limelight
/show/listecho "Downloading limelight $version" $OK
wget https://github.com/irtimmer/moonlight-embedded/releases/download/v$version/limelight.jar -O /opt/limelight/limelight.jar
wget https://github.com/irtimmer/limelight-embedded/releases/download/v$version/libopus.so -O /opt/limelight/libopus.so
